### ISSUE TITLE
About FlutterAutoGUI.write

### ISSUE THREAD

**Issue by ggugyi96** [Chappie74/flutter_auto_gui#4]
Thank you very much for this useful dependency. But I want it to be written in Chinese. After trying to input Chinese, I found that it cannot be written in Chinese. Is there any way to write in Chinese?

**Comment by Chappie74** [comment]
I am not sure. Seems like it's not supported in PyAutoGui, which is the library I based this off of. 

https://github.com/asweigart/pyautogui/issues/237
